export const RECEIVE_PLACES = 'RECEIVE_PLACES'
export const RECEIVE_PLACE = 'RECEIVE_PLACE'
export const RECEIVE_PLACE_PHOTOS = 'RECEIVE_PLACE_PHOTOS'

export const LIKE_PLACE = 'LIKE_PLACE'
export const DISLIKE_PLACE = 'DISLIKE_PLACE'
